=== uk-gov-mirror/hmcts.cpp-context-sjp/sjp-json/src/main/resources/json/schema/commands/update-session-bdf.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/commands/sjp.update-session-bdf.json",
  "type": "object",
  "properties": {
    "sessionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "magistrate": {
      "type": "string"
    },
    "courtHouseCode": {
      "type": "string"
    },
    "courtHouseName": {
      "type": "string"
    },
    "localJusticeAreaNationalCourtCode": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": ["MAGISTRATE", "DELEGATED_POWERS", "AOCP"]
    },
    "legalAdviserUserId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    }
  },
  "required": [
    "sessionId"
  ],
  "additionalProperties": false
}

=== uk-gov-mirror/hmcts.cpp-context-sjp/sjp-command/sjp-command-handler/src/raml/json/sjp.command.update-session-bdf.json
{
  "sessionId": "c70867c0-3d9b-4cd4-978d-056a2915bb75",
  "magistrate": "Alan Smith",
  "courtHouseCode": "B01LY",
  "courtHouseName": "Coventry Magistrates' Court",
  "localJusticeAreaNationalCourtCode": "2924",
  "type": "MAGISTRATE",
  "legalAdviserUserId": "31ec3a16-8721-498c-8da5-f099390ee254"
}
